---
  - name: My first playbook
    hosts: webservers
    become: true
    tasks:
  
    - name: Install appache httpd (state=present is optional)
      apt:
       name: apache2
       state: present

